In [15]:
#ARITMETIK ORTALAMA

"""İstatistikte verilerin merkezine ilişkin bilgi veren ölçülere "merkezi eğilim ölçüleri (measures of central tendency)" 
denilmektedir. Merkezi eğilim ölçülerinin en yaygın kullanılanı aritmetik ortalamadır """
import statistics      #mean fonksiyonu herhangi bir iterable nesneyi parametre olarak alabilmektedir.
a = [1, 2, 7, 8, 1, 5] 
statistics.mean(a)

4

In [6]:
#NumPy kütüphanesindeki mean fonksiyonu axis temelinde (yani satırsal ve sütunsal biçimde) ortalama hesaplayabilmektedir. 
#Örneğin:
import numpy as np
a = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10]])
print(np.mean(a, axis=0))

[4.66666667 5.66666667 6.66666667]


In [7]:
#NumPy'da mean fonksiyonu aynı zamanda ndarray sınıfının metodu biçiminde de bulunmaktadır. Örneğin:
import numpy as np
a = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10]])
print(a)
a.mean(axis=0) #axis=0 ==> sutuna gore ortalama aliyor 


[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


array([4.66666667, 5.66666667, 6.66666667])

In [8]:
#Pandas kütüphanesinde Series ve DataFrame sınıflarının mean metotları aritmetik ortalama hesabı yapmaktadır. DataFrame 
#sınıfının mean metodunda default axis 0 biçimindedir. Yani sütunsal ortalamalar elde edilmektedir. Örneğin:
import pandas as pd
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(df)
print("**")
print(df.mean())
# Aritmetik ortalama aralıklı (interval) ve oransal (ratio) ölçeklere uygulanabilir. Aritmetik ortalama O(N) karmaşıklıkta yapılmaktadır.

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
**
0    4.0
1    5.0
2    6.0
dtype: float64


In [ ]:
#MEDYAN

"""Diğer bir merkezi eğilim ölçüsü de "medyan (median)" denilen ölçüdür. Medyan sayıların küçükten büyüğe sıraya dizildiğinde 
ortadaki değerdir. Ancak sayılar çift sayıda ise sayıların tam ortasında bir değer olmadığı için ortadaki iki değerin aritmetik 
ortalaması medyan olarak alınmaktadır. Medyan işlemi uç değerlerden (outliers) etkilenmez. Ancak medyan işlemi aritmetik 
ortalamadan daha fazla zaman alan bir işlemdir. Çünkü medyan için önce değerlerini sıraya dizilmesi gerekmektedir. Dolayısıyla 
medyan işlemi O(N log N) karmaşıklıta bir işlemdir. Medyan işlemi Python'ın standard kütüphanesinde statistics modülü içerisindeki 
median isimli fonksiyonla yapılabilmektedir."""

In [9]:
import statistics
a = [1, 23, 56, 12, 45, 21]
print(statistics.median(a))

22.0


In [13]:
#NumPy kütüphanesinde medyan işlemi eksensel biçimde median fonksiyonuyla yapılabilmektedir. Örneğin:

import numpy as np
a = np.random.randint(1, 100, (10, 10))
print(a) 
print("***")
print(np.median(a, axis=0))

[[94 14  7 50 46 69 58 30 69 49]
 [62  8  7 26 59  8 35 48  2 31]
 [68 88 15 49 87 60 39 75 43 96]
 [61 57 58 22 23 96 13 67 88 71]
 [29 82 81  6 45 47 73 19 75 91]
 [27 65  7 41 87 61 56 94 24  7]
 [26 71 39 39 98  9 77 86 64 91]
 [65 52 74 10 88 80 45 68 33 78]
 [52 58 98 15 88 95  3  3  4 49]
 [ 3 73 13 27 74 50 55  8 94 21]]
***
[56.5 61.5 27.  26.5 80.5 60.5 50.  57.5 53.5 60. ]


In [ ]:
""" ndarray sınıfının median isimli bir metodu yoktur.
#Benzer biçimde Pandas kütüphanesinde de Series ve DataFrame sınıflarının median isimli metotları eksensel median işlemi 
yapabilmektedir. Tabii DataFrame sınıfının median metodunun default ekseni yine 0'dır (yani sütunsal işlem yapılmaktadır).Tabii median işlemi de ancak sayısal verilere yani aralıklı ve oransal ölçeklere uygulanabilir.""" 

In [22]:
import numpy as np
a = np.random.randint(1, 100, (10, 10))
print(a) 
print("*********")
df = pd.DataFrame(a)
print(df)
print("*********")
print(df.median())


[[16 54 27 30 54 40 18 13 32 94]
 [67 32 51 89 80  2 42 68 75 61]
 [60 59 48 59  3 40 78  6 55 26]
 [19 44 69 57 20 35 46 23 76 50]
 [24 19 12 10 79 54 85 96 31 48]
 [96 23 17 90 93 43 92 20 71 86]
 [61 84 92 37 92 60 34 70 98  8]
 [66 60 47 64 75 27 98 84 87 81]
 [55 77 48 91 53 48  9 83 17 83]
 [29 89 48  4 99  9 98 29 95 62]]
*********
    0   1   2   3   4   5   6   7   8   9
0  16  54  27  30  54  40  18  13  32  94
1  67  32  51  89  80   2  42  68  75  61
2  60  59  48  59   3  40  78   6  55  26
3  19  44  69  57  20  35  46  23  76  50
4  24  19  12  10  79  54  85  96  31  48
5  96  23  17  90  93  43  92  20  71  86
6  61  84  92  37  92  60  34  70  98   8
7  66  60  47  64  75  27  98  84  87  81
8  55  77  48  91  53  48   9  83  17  83
9  29  89  48   4  99   9  98  29  95  62
*********
0    57.5
1    56.5
2    48.0
3    58.0
4    77.0
5    40.0
6    62.0
7    48.5
8    73.0
9    61.5
dtype: float64


In [14]:
#MOD :
""" Merkezi eğilim ölçülerinin bir diğeri de "mod" denilen ölçüdür. Bir grup verideki en çok yinelenen değere "mod (mode)" 
    denilmektedir. Mod özellikle kategorik ve sıralı ölçeklerde ortalamanın yerini tutan bir işlem olarak kullanılmaktadır. 
    Mod işlemi genel olarak O(N log N) karmaşıklıkta yapılabilmektedir. (Tipik mod algoritmasında değerler önce sıraya dzilir.
    Sonra yan yana aynı değerlerden kaç tane olduğu tespit edilir.) Mod işlemi Python standart kütüphanesindeki statistics
    modülünde bulunan mode fonksiyonuyla yapılabilir. Örneğin:
"""

import statistics
a = [1, 3, 3, 4, 2, 2, 5, 2, 7, 9, 5, 3, 5, 7, 5]
print(statistics.mode(a)) 

5


In [16]:
"""Eğer en çok yinelenen değer birden fazla ise mode fonksiyonu dizilimde ilk karşılaşılan en çok yinelenen değere geri
    dönmektedir. 

    NumPy kütüphanesinde mod işlemini yapan bir fonksiyon bulunmamaktadır. Ancak SciPy kütüphanesinde mod işlemi için stats
    modülü içerisindeki mode fonksiyonu kullanılabilir. Bu fonksiyon yine eksensel işlemler yapabilmektedir. mode fonksiyonu 
    ModeResult isimli bir sınıf türünden tuple sınıfından türetilen bir sınıf türünden bir nesne verir. Bu sınııfın mode ve 
    count örnek öznitelikleri en çok yinelenen değerleri ve onların sayılarını bize vermektedir. ModeResult sınıfı bir çeşit
    demet özelliği gösterdiği için demet gibi de kullanılabilir. 
"""

import scipy.stats
import numpy as np
a = np.random.randint(1, 10, (20, 10))
print(a)
mr = scipy.stats.mode(a, axis=0 , keepdims=True)
print("Mode :")
print(mr.mode)
print("Mode Count : ")
print(mr.count)

[[1 1 8 4 4 5 6 7 2 4]
 [8 2 8 9 9 7 5 4 7 9]
 [7 5 7 2 3 8 5 1 5 8]
 [4 6 6 6 8 5 2 3 7 6]
 [9 9 6 1 7 4 1 9 3 8]
 [8 8 8 8 4 7 4 7 5 9]
 [6 2 2 6 8 5 3 5 8 8]
 [6 2 7 8 2 6 3 1 6 7]
 [1 4 2 4 6 5 6 2 7 4]
 [9 5 9 8 5 1 1 7 9 9]
 [3 8 7 2 5 3 6 6 9 6]
 [7 7 1 1 1 5 9 1 1 1]
 [6 9 9 9 3 4 3 7 3 6]
 [6 8 4 5 6 2 4 5 2 6]
 [5 8 7 8 6 2 9 7 8 4]
 [5 9 4 6 6 5 3 4 4 1]
 [8 3 6 8 6 5 8 8 1 8]
 [4 7 8 8 7 2 4 9 9 6]
 [4 6 2 4 8 4 1 4 1 5]
 [1 7 7 5 6 8 2 3 8 9]]
Mode :
[[6 8 7 8 6 5 3 7 1 6]]
Mode Count : 
[[4 4 5 6 6 7 4 5 3 5]]


In [18]:
"""  Pandas kütüphanesinde Series ve DataFrame sınıflarının mode metotları da mode işlemi yapmaktadır."""
""" DataFrame sınıfının mode metodu bize bir DataFrame nesnesi vermektedir. Uygulamacı genellikle bunun ilk satırı ile ilgilenir. 
    Diğer satırlar eşit miktarda tekrarlanan elemanlardan oluşmaktadır. Tabii belli bir sütunda eşit miktarda tekrarlanan elemanların
    sayısı az ise artık geri döndürülen DataFrame'in o sütuna ilişkin satırlarında NaN değeri bulunacaktır"""
import numpy as np
import pandas as pd
a = np.random.randint(1, 10, (20, 10))
df = pd.DataFrame(a)
print(df)
print("Mode :")
print(df.mode()) 



    0  1  2  3  4  5  6  7  8  9
0   2  4  9  3  3  1  7  5  5  2
1   1  5  9  6  4  5  5  1  7  1
2   9  4  6  8  4  3  4  8  1  7
3   1  2  6  5  1  4  9  1  2  2
4   7  6  6  9  5  4  6  7  1  1
5   7  6  7  5  1  7  2  1  1  8
6   3  7  4  1  6  1  9  4  9  4
7   9  7  7  1  6  9  1  2  5  7
8   6  4  9  3  6  8  3  1  1  2
9   7  7  9  6  4  9  1  2  4  2
10  9  3  9  2  5  1  1  7  8  3
11  7  7  4  7  6  5  8  4  7  8
12  6  1  5  2  7  5  4  9  8  3
13  9  3  5  7  8  9  2  1  3  5
14  4  6  9  2  7  4  8  7  5  5
15  8  1  7  5  9  4  3  8  9  4
16  4  2  4  4  8  8  4  6  5  2
17  8  1  5  2  1  4  8  2  1  3
18  9  1  8  9  1  2  5  3  4  5
19  1  3  1  4  9  9  2  5  1  5
Mode :
     0    1    2    3    4    5  6    7    8    9
0  9.0  1.0  9.0  2.0  1.0  4.0  1  1.0  1.0  2.0
1  NaN  7.0  NaN  NaN  6.0  NaN  2  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  4  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  NaN  8  NaN  NaN  NaN


In [20]:
"""  Değerlerin merkezine ilişkin bilgiler dağılım hakkında iyi bir fikir vermeyebilir. Örneğin iki ülkede kişi başına düşen 
    ortalama yıllık gelir (gayri safi milli hasıla) 15000 dolar olabilir. Ancak bu iki ülke arasında gelir dağılımında önemli 
    farklılıklar bulunuyor olabilir. O halde değerlerin ortalamasının yanı sıra onların ortalamaya göre nasıl yayıldıkları da 
    önemlidir. İstatistikte değerlerin ortalamaya göre yayılımı için "merkezi yayılım ölçüleri (measures of dispersion)" denilen 
    bazı ölçüler kullanılmaktadır. Merkezi yayılım ölçüleri aslında değerlerin ortalamadan ortalama uzaklığını belirlemeyi hedeflemektedir. 

    Eğer biz değerlei ortalamadan çıkartıp onların ortalamasını alırsak 0 elde ederiz. Aşğıdaki programda değerlerin ortalamadan
    uzaklıklarının ortaalaması bulunmuştur. (Bu tür durumlarda yuvarlama hatalarından dolayı sıfır yerine sıfıra çok yakın 
    değerler elde edilebilir."""

import numpy as np

a = np.array([1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8])
mean = np.mean(a)
print(mean)

result = np.mean(a - mean)
print(result) 

5.0
0.0


In [21]:

"""Merkezi yayılım ölçüsü olarak "değerlerin ortalamadan ortalama mutlak uzaklığına" başvurulabilir. Burada mutlak değer 
    alınmasının nedeni uzaklıkları negatif olmaktan kurmak içinidir. Bu durumda ortalama 0 çıkmaz. Ancak bu yöntem de aslında 
    çok iyi bir yöntem değildir. Aşağıda aynı dilimin ortalamadan ortalama mutlak uzaklığı hesaplanmışır."""
import numpy as np

a = np.array([1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8])
mean = np.mean(a)
print(mean)

result = np.mean(np.abs(a - mean))
print(result)               # 2.5

5.0
2.5


In [28]:
"""  Standart sapmanın karesine "varyans (variance)" denilmektedir. Varyans işlemi standart kütüphanedeki statistics modülünde 
    bulunan variance ve pvariance fonksiyonlarıyla yapılmaktadır. NumPy kütüphanesinde varyans işlemi var fonksiyonuyla ya da 
    ndarray sınıfının var metoduyla, Pandas kütüphenesinin Series ve DataFrame sınıflarındaki var metoduyla yapılmaktadır.
    Yine NumPy'daki variance fonksiyonundaki ddof default olarak 0, Pandas'taki ddof ise 1'dir.

    Pekiyi neden standart sapma varken ayrıca onun karesi için varyans terimi uydurulmuştur? İşte istatistikte pek çok durumda
    aslında doğrudan ortalamadan farkların karesel ortalamaları (yani standart sapmanın karesi) kullanılmaktadır. Bu nedenle 
    bu hesaba ayrı bir isim verilerek anlatımlar kolaylaştırılmıştır.""" 

import statistics
import numpy as np
import pandas as pd

data = [1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8]

result = statistics.pvariance(data)
print(result)               # 7.666666666666667

result = np.var(data)
print(result)               # 7.666666666666667

s = pd.Series(data)
result = s.var(ddof=0)
print(result)               # 7.666666666666667

7.666666666666667
7.666666666666667
7.666666666666667


In [ ]:
""" 
Bir deney sonucunda oluşacak durum baştan tam olarak belirlenemiyorsa böyle deneylere "rassal deney (random experiment)"
    denilmektedir. Örneğin bir paranın atılması deneyinde para "yazı" ya da "tura" gelebilir. O halde "paranın atılması" 
    rassal bir deneydir. Benzer biçimde bir zarın atılması, bir at yarışında hangi atın birinci olacağı gibi deneyler rassal 
    deneylerdir. Bir deneyin sonucu öndecen bilinebiliyorsa bu tür deneylere "deterministik deneyler" de denilmektedir. 
    Bazı bilimlerdeki süreçler deterministiktir. Ancak bazı bilimlerdeki süreçlerin sonucunda oluşacak durumlar önceden 
    tam olarak kestirilememektedir. Önceden sonucu tam olarak kestirilemeyen süreçlere "olasılıksal (probabilistic)" ya da 
    "stokastik (stochastic)" süreçler denilmektedir. 

    Deterministik süreçlerle olasılıksal süreçler aslında üzerinde çok düşünülmüş konulardandır. Kimilerine göre olasılıksal 
    süreç diye bir şey yoktur. Her şey deterministiktir. Bir sürecin olasılıksal olması sadece "bizim onun sonucunu belirleyemememizden"
    kaynaklanmaktır. Örneğin paranın atılması sırasındaki tüm bilgilere sahip olsak artık bu deneyin sonucu olasılıksal değil
    deterministik hale gelecektir. Tabii evrende kaotik bir süreçler söz konusudur. Yani bir olay başka bir olayı etkilemekte
    ve küçük değişiklikler büyük sonuçlara yol açabilmektedir. Buna feslefede "kaos teorisi" halk arasında da "kelebek etkisi"
    denilmektedir. Eğer evrende mutlak bir determinizm varsa evren reset konumuna alındığında yine bugüne her şey kurulu bir 
    biçimde gelecektir. 
    
    
    Bir rassal deney sonucunda oluşabilecek tüm olası durumların kümesine "örnek uzayı (sample space)" denilmektedir. Örneğin 
    bir paranın atılması deneyinde örnek uzayı S = { Yazı, Tura} biçimindedir. Biz zarın atılması deneyindeki örnek uzayı ise
    S = {1, 2, 3, 4, 5, 6} biçimindedir. İki zarın atılmasındaki örnek uzayı S = {(1, 1), (1, 2), (6, 5), (6, 6)} biçimindedir.

    Örnek uzayın her bir alt kümesine "olay (event)" denilmektedir. Örneğin bir zarın atılmasındaki bazı olaylar şunlar olabilir:

    E1 = {1, 3}
    E2 = {3, 4, 5}
    E3 = {6}

    Bir kümenin bütün alt kümelerine o kümenin "kuvvet kümesi (power set)" denilmektedir. Bir rassal deneydeki bütün olaylar
    kuvvet kümesi içerisindeki olaylardır. Bir kümenin tüm alt kümelerinin sayısı 2 ** n tanedir. 

    Örnek uzayın tek elemanlı olaylarına (yani alt kğmelerine) "basit olay (simple events)" denilmektedir. Örneğin paranın 
    atılması deneyindeki basit olaylar {Yazı} ve {Tura} biçimindedir. 
    
"""

In [ ]:
"""

Olasılığın (probablity) değişik tanımları yapılabilmektedir. Olasılığın en yaygın tanımlarından birisi "göreli sıklık 
    (relative frequency)" tanımıdır. Bu tanıma göre bir rassal olay çok sayıda yinelendikçe elde edilen olasılık değeri belli bir değere 
    yakınsamaya başlar. Örneğin bir paranın 100 kere atılmasında 50 kere yazı 50 tura gelmeyebilir. Ancak para sonsuz sayıda 
    atılırsa (ya da çok fazla sayıda atılırsa) tura gelme sayısının paranın atılma sayısına oranı 0.5'e yakınsayacaktır. Buna 
    istatistike "büyük sayılar yasası (law of large numbers)" da denilmektedir. 

    Aşağıdaki örnekte bir para değişik miktarlarda yazı tura biçiminde atılmıştır. Elde edilen oranlar gitgide 0.5'e yakınsayacaktır.
    Programın çalıştırılmasıyla şu değerler elde edilmiştir:

    head = 0.4, tail = 0.6
    head = 0.5, tail = 0.5
    head = 0.479, tail = 0.521
    head = 0.4977, tail = 0.5023
    head = 0.50005, tail = 0.49995
    head = 0.500075, tail = 0.499925
    head = 0.5002417, tail = 0.4997583
    head = 0.49997078, tail = 0.50002922


"""    


In [4]:
import random

HEAD = 1

def head_tail(n):
    head = tail = 0

    for _ in range(n):
        val = random.randint(0, 1)
        if val == HEAD:
            head += 1
        else:
            tail += 1
            
    return head / n, tail / n
            
        
head, tail = head_tail(10)
print(f'head = {head}, tail = {tail}')        

head, tail = head_tail(100)
print(f'head = {head}, tail = {tail}') 

head, tail = head_tail(1000)
print(f'head = {head}, tail = {tail}') 

head, tail = head_tail(10_000)
print(f'head = {head}, tail = {tail}') 

head, tail = head_tail(100_000)
print(f'head = {head}, tail = {tail}') 

head, tail = head_tail(1_000_000)
print(f'head = {head}, tail = {tail}') 

head, tail = head_tail(10_000_000)
print(f'head = {head}, tail = {tail}') 

head, tail = head_tail(100_000_000)
print(f'head = {head}, tail = {tail}') 


head = 0.4, tail = 0.6
head = 0.46, tail = 0.54
head = 0.488, tail = 0.512
head = 0.5052, tail = 0.4948
head = 0.49885, tail = 0.50115
head = 0.499655, tail = 0.500345
head = 0.4999709, tail = 0.5000291
head = 0.49989769, tail = 0.50010231


In [ ]:
"""
    Olasılığın temel matematiksel teorisi Kolmogorov tarafından oluşturulmuştur. Kolmogorov üç aksiyom kabul edildiğinde bütün
    olasılık kurallarının teoremiispat biçiminde açıklanabileceğini göstermiştir. Kolmogorov'un üç aksiyomu şöyledir:

    1) Örnek uzayının olsılığı 1'dir. Yani P(S) = 1'dir. Buradan olasılığın en yüksek değerinin 1 olacağını ve tüm örnek uzayının 
    olma olasılığının 1 olduğunu anlamalıyız. Örneğin bir zarın atılmasındaki örnek uzayı {1, 2, 3, 4, 5, 6} biçimindedir. 
    P({1, 2, 3, 4, 5, 6}) = 1'dir. Buradaki P({1, 2, 3, 4, 5, 6}) bir zarın 1 ya da 2 ya da 3 ya da 4 ya da 5 ya da 6 gelme olasılığı 
    anlamındadır. 

    2) Herhangi bir olayın olasılığı 0 ya da 0'dan büyüktür. Yani P(E) >= 0'dır. Burada olasılığın en düşük değerinin 0 olduğu 
    belirtilmektedir. O halde olasılık değeri 0 iel 1 arasındadır. 

    3) Bir kümenin olasılığı demek rassal deney sonucunda o kümenin herhangi elemanının oluşma olasılığı demektir. Örneğin 
    zarın atılmasındaki P({3, 5}) olasılığı zarın üç ya da 5 gelme olasılığı anlamına gelir. İki küme ayrıksa (yani ortak elemanları)
    yoksa Bu iki kğmenin birleşimlerinin olasılığı bu iki kğmenin olaıslık toplamlarına eşittir. Yani E1 ve E2 iki olay 
    olmak üzere eğer bu iki olay ayrıksa (yani E1 ⋂ E2 = ∅ ise) P{E1 ∪ E2} = P{E1} + P{E2}'dir.

    Bu üç kural kabul edildiğinde kümeler teorisi, permütasyon, kombinasyon gibi işlemlerle tüm olasılk formülleri elde edilebilmektedir.

"""

In [27]:
#STANDART SAPMA

"""  Aslında ortalamadan ortalama uzaklık için "standart sapma (standard deviation)" denilen ölçü tercih edilmektedir. Standart 
    sapmada ortalamadan uzaklıkların mutlak değeri değil kareleri alınarak negatiflikten kurtulunmaktadır. Kare alma işlemi 
    değerleri daha fazla farklılaştırmaktadır. Yani aynı değerlerin oluşma olasılığı kare alma sayesinde daha azalmaktadır. 
    Aynı zamanda bu işlem bazı durumlarda başka faydalara da yol açmaktadır. 
    (Örneğin ileride bu kare alma işlemlerinin optimizasyon problemlerinde uygun bir işlem olduğunu göreceğiz.)

    Standart sapma, değerlerin ortalamadan farklarının karelerinin ortalamasının karekökü alınarak hesaplanmaktadır.
    Ancak burada ortalama bulunurken değer sayısı n olmak üzere bölüm n'e ya da (n - 1)'e yapılabilmektedir. 
    Anakütle (population) için genellikle n'e bölme yapılırken örneklemden hareketle ana kütle standart sapmasının tahmin edileceği durumlarda (n - 1)'e bölme yapılmaktadır. 
    (n - 1)'e bölme işlemine "Bessel düzeltmesi (Bessel's correction)" denilmektedir.
    Genellikle standart sapma hesaplayan fonksiyonlar kaça bölüneceğini "ddof (delte degrees of freedom)" parametresiyle programcııdan istemektedir. ddof değeri n eksi kaça bçlüneceğini 
    belirtir. Örneğin ddof=0 ise n'e bölme ddof=1 ise (n - 1)'e bölme uygulanır. 

    Aşağıdaki örnekte NumPy kullanılarak bir standart sapma hesaplayan fonksiyon yazılmıştır. """

import numpy as np
def sd(a, ddof = 0):
    return np.sqrt(np.sum((a - np.mean(a)) ** 2)  / (len(a)  - ddof))

a = [1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8]
result = sd(a)
print(result)
print("***")

"""    NumPy kütüphanesinde std isimli fonksiyon eksensel standart sapma hesaplayabilmektedir. Fonksiyonun ddof parametresi 
    default durumda 0'dır. Yani default durumda fonksiyon n'e bölme yapmaktadır.""" 
import numpy as np
a = np.array([1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8])
result = np.std(a)
print(result) 
print("***")
""" Pandas kütüphanesinde de Series ve DataFrame sınıflarının std isimli metotları eksensel standart sapma hesabı yapabilmektedir. 
    Ancak bu metotlarda ddof parametresi default 1 durumundadır. Yani bu metotlar default durumda (n - 1)'e bölme yapmaktadır."""
import pandas as pd

s = pd.Series([1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8])
result = s.std()
print(result)    

s = pd.Series([1, 4, 6, 8, 4, 2, 1, 8, 9, 3, 6, 8])
result = s.std(ddof=0) #ddof=0 n'e bolunmek demek
print(result) 


2.7688746209726918
***
2.7688746209726918
***
2.891995221924885
2.7688746209726918


In [ ]:
 #RASSAL DEGISKEN : 
    
"""
   Olasılıkta ve istatistikte en çok kullanılan temel kavramlardan biri "rassal değişken (random variable)" denilen kavramdır. 
    Her ne kadar "rassal değişken" isminde bir "değişken" geçiyorsa da aslında rassal değişken bir fonksiyon belirtmektedir.
    
    Rassal değişken bir rassal deney ile ilgilidir. Bir rassal deneyde örnek uzayın her bir elemanını (yani basit olayını)
    reel bir değere eşleyen bir fonksiyon belirtmektedir. Rassal değişkenler genellikle "sözel biçimde" ifade edilirler. 
    Ancak bir fonksiyon belirtirler. Rassal değişkenler matematiksel gösterimlerde genellikle büyük harflerle belirtilmektedir. 
    Örneğin:

    - R rassal değişkeni "iki zar atıldığında zaarların üzrindeki sayıların toplamını" belirtiyor olsun. Burada aslında R 
    bir fonksiyondur. Örnek uzayın her bir elemanını bir değere eşlemektedir. Matematiksel gösterimle R rassal değişkeni
    şöyle belirtilebilir:

    R: S -> R

    Burada R'nin  örnek uzayından R'ye bir fonksiyon belirttiği anlaşılmaıdır. Burada R fonksiyonu aşağıdaki gibi eşleme 
    yapmaktadır:

    (1, 1) -> 2
    (1, 2) -> 3
    (1, 3) -> 4
    ...
    (6, 5) -> 11
    (6, 6) -> 12

    K rassal değişkeni "rastgele seçilen bir kişinin kilosunu belirtiyor" olsun. Bu durumda örnek uzayı aslında dünyaki 
    tüm insanlardır. Burada K fonksiyonu da her insanı onun kilosuna eşleyen bir fonksiyondur. 

    C rassal değişkeni "rastgele seçilen bir rengin RGB değerlerinin ortalamasını" belirtiyor olsun. Bu duurmda her rengin
    bir RGB ortalaması vardır. Bu fonksiyon belli bir rengi alıp onun ortalamasını belirten bir sayıya eşlemektedir. 

    Rassal değişkenler kümeler üzerinde işlemler yapmak yerine gerçek sayılar üzerinde işlem yapmamızı sağlayan, anlatımlarda
    ve gösterimlerde kolaylık sağlayan bir kavramdır.  
"""


"""
 Her rassal değişkenin belli bir değer almasının bir olasılığı vardır. Örneğin "iki zarın atılması deneyinde üste gelen sayılar
    toplamına ilişkin" R rassal değişkenini düşünelim. P(R = 5) demek S örnek uzayındaki 5 değerini veren kümenin olsılığı demektir. 
    Yani P(R = 5) ile aslında P({(1, 4), (4, 1) (2, 3), (3, 2)}) aynı anlamdadır. Buradaki P({(1, 4), (4, 1) (2, 3), (3, 2)}) olasılığın
    "bu değerlerden herhangi birinin oluşmasına yönelik" olasılık olduğunu anımsayınız. Bu olasılığın değeri 1/9'dur.

    Bir rassal değişkenin olasılığı belirtilirken P harfi olsılığı anlatmaktadır. Ancak bu P harfinden sonra bzı kişiler normal 
    parantezleri bazı kişiler küme parantezlerini tercih ederler. Yani örneğin bazı kişiler P(R = 5) gibi bir gösterimi tercih
    derken bazı kişiler P{R = 5} gösterimini tercih etmektedir. Küme parantezli gösterim aslında "R = 5" ifadesinin bir küme 
    belirttiğini ve bu kümenin olasılığının hesaplanmak istediğini" belirtmesi açısından daha doğal gibi gözükmektedir. 

    K rassal değişkeni rastgele seçilen bir insanın kilosunu belirtiyor olsun. Bu durumda K aslında tüm insanları tek tek 
    onların kilolarına eşleyen bir fonksiyondur. O halde P{K < 60} olasılığı aslında "rastgele seçilen bir kişinin kilosunun 
    60'tan küçük olması olasılığı" anlamına gelmektedir. 
"""

In [ ]:
"""
    Rassal değişkenler tıpkı matematiksel diğer fonksiyonlarda olduğu gibi "kesikli (discrete)" ya da "sürekli (continuous)" 
    olabilmektedir. eğer bir rassal değişken (yani fonksiyon) teorik olarak belli bir aralıkta tüm gerçek sayı değerlerini 
    alabiliyorsa böyle rassal değişkenlere "sürekli (continous)" rassal değişkenler denilmektedir. Ancak bir rassal değişken
    belli bir aralıkta yalnızca belli gerçek sayı değerlerini alabiliyorsa bu rassal değişkenlere "kesikli (discrete)" rassal
    değişkenler denilmektedir.
    
    Örneğin "iki zarın atılmasında üste gelen sayılar toplamını belirten R rassal değişkeni" kesiklidir. 
    Çünkü yalnızca belli değerleri alabilmektedir. Ancak "rastgele seçilen bir kişinin kilosunu belirten" K rassal değişkeni
    süreklidir.
    Çünkü teorik olarak belli bir aralıkta tüm gerçek değerleri alabilir. (Biz kişilerin kilolarını yuvarlayarak ifade
    etmekteyiz. Ancak aslında onların kiloları belli aralıktaki tüm gerçek değerlerden biri olabilir.)

    Sürekli rassal değişkenlerin noktasal olasılıkları 0'dır. Örneğin "rastgele seçilen kişinin kilosunu" belirten K rassal
    değişkeni söz konusu olsun. P{K = 67} gibi bir olasılık aslında 0'dır.
    Çünkü gerçek sayı ekseninde sonsuz tane nokta vardır. 67 yalnızca bu sonsuz noktadan bir tanesini belirtir. 
    
    Sayı / sonsuz da 0'dır. Ancak sürekli rassal değişkenlerin aralıksal olasılıkları 0 olmak zorunda değildir.
    Yani örneğin P{66 < K < 67} olasılığı 0 değildir. Burada {66 < K < 67} kümesinin de 
    elemanlarının sonsuz sayıda olduğuna dikkat ediniz. Artık bu hesap matematikte "limit, türev, integral" konularıyla 
    ilişkili hale gelmektedir. Sürekli rassal değişkenlerin aralıksal olasılıklarını belirtirken aralıklardaki '=' sembolünün 
    bir anlamının olmayacağına dikkat ediniz. Örneğin P{66 < K < 67} ile P{66 <= K <= 67} arasında aslında bir fark yoktur. 
    Bu konuda da kişiler farklı gösterimleri tercih edebilmektedir. Bazı kişiler bir tarafa '=' sembolünü koyup diğer tarafa
    koymamaktadır. Örneğin P{66 <= K < 67} gibi. Ancak bu '=' sembollerinin sürekli rassal değişkenlerde bir etkisi yoktur.

"""

In [ ]:
#PDF taniimi 

"""
    # Yapay zeka ve makine öğrenmesinde sürekli rassal değişkenler daha fazla karşımıza çıkmaktadır. 
    Bu nedenle  biz sürekli rassal değişkenler ve onların olasılıkları üzerinde biraz daha duracağız. 

    #PDF:
    Sürekli bir rassal değişkenin aralıksal olasılıklarını hesaplama aslında bir "integral" hesabı akla getirmektedir.
    İşte  sürekli rassal değişkenlrin aralıksal olasılıklarının hesaplanması için kullanılan fonksiyonlara "olasılık yoğunluk 
    fonksiyonları (probability density functions)" denilmektedir.
    
    
    Birisi bize bir rassal değişkenin belli bir aralıktaki 
    olasılığını soruyorsa o kişiin bize o rassal değişkene ilişkin "olasılık yoğunluk fonksiyonunu" vermiş olması gerekir. 
    Biz de örneğin P{x0 < X < x1} olasılığını x0'dan x1'e f(x)'in integrali ile elde ederiz. 

    Bir fonksiyonun olasılık yoğunluk fonksiyonu olabilmesi için -sonsuzdan + sonsuze integralinin (yani tüm eğri altında kalan
    alanın) 1 olması gerekir. Bir rassal değişkenin olasılık yoğunluk fonksiyonuna "o rassal değişkenin dağılımı" da denilmektedir.


    Pekiyi mademki bizim bir rassal değişkenin aralıksla olasılığını elde etmek için bir olasılık yoğunluk fonksiyonuna ihtiyacımız
    var o halde bu fonksiyonu nasıl elde edeceğiz? İşte pek çok rassal değişkenin olasılık yoğunluk fonksiyonunun bazı kalıplara
    uyduğu görülmektedir. 
    
    Örneğin doğadaki pek çok olgunun (boy gibi, kilo gibi, zeka gibi) olasılık yoğunluk fonksiyonu 
    "normal dağılım" denilen eğriye uymaktadır. Normal dağılım eğrisine "Gauss eğrisi" ya da "çan eğrisi" de denilmektedir. 
    Ancak yukarıda da belirttiğimiz gibi aslında çeşitli olaylara uygulanabilecek değişik olasılık yoğunluk fonksiyonu kalıpları
    belirlenmiştir. Tabii bu eğriler birer kalıptır. 
    Dolayısıyla bazı parametrelere de sahiptir. Örneğin sonsuz sayıda Gauss eğrisi oluşturulabilir. Gauss eğtisinin iki öenmli parametrik bilgisi "orta noktasını belirten "ortalama" ve zayıflığını ya da 
    şişmanlığını belirten "standart sapma" değeridir. 
    
    Bu durumda örneğin sürekli rassal değişkenlerle ilgili bir soru şöyle olabilir: "Kişlerin zekaları ortalaması 100 standart 
    sapması 15 olan normal dağılıma uygundur. Rastgele seçilen bir kişinin zekasının 120 ile 130 arasında olma olasılıı nedir?" 
    Burada bize rassal değişkenin olasılık yoğunluk fonklsiyonu parametreleriyle verilmiştir. Bizim de bu olasılığı hesaplamak
    için tek yapacağımız şey 120'den 130'a fonksiyonun integralini almaktır. 

    Pekiyi rassal değişkenimiz başkaları tarafından belirlenen herhangi bir kalıba uymuyorsa ne yapabiliriz? Bir rassal 
    değişkenin olasılık yoğunluk fonksiyonunun sıfırdan çıkarılması biraz zahmetli bir işlemdir. Kümülatif olasılıklar yardımıyla
    olasılık yoğunluk fonksiyonları tatmin edici bir biçimde elde edilebilmektedir. Ancak yukarıda da belirttiğimiz gibi
    aslında pek çok olay zaten tespit edilmiş çeşitli kalıplara uymaktadır.

"""