In [1]:
#Ordinal encoder 
"""
Sıralı (ordinal) verilerin sayısal biçime dönüştürülmesi tipik olarak düşük sıranın düşük numarayla ifade edilmesi biçiminde 
olabilir. Örneğin "Eğitim Durumu", "ilkokul", "ortaokul", "lise", "üniversite" biçiminde dört kategoride sıralı bir bilgi 
olabilir. Biz de bu bilgilere sırasıyla birer numara vermek isteyebiliriz. Örneğin:

İlkokul     --> 0
Ortaokul    --> 1
Lise        --> 2
Üniversite  --> 3

scikit-learn içerisindeki LabelEncoder sınıfı bu amaçla kullanılamamaktadır. Çünkü LabelEncoder etiketlere rastgele numara 
vermektedir. scikit-learn içerisinde bu işlemi pratik bir biçimde yapan hazır bir sınıf bulunmamaktadır. Gerçi scikit-learn 
içerisinde OrdinalEncoder isimli bir sınıf vardır ama o sınıf bu tür amaçları gerçekleştirmek için tasarlanmamıştır. 
"""

#ordinal encoderin label encoderden farki birden fazla sutunda calismak

In [ ]:
"""
OrdinalEncoder sınıfının kullanımı benzerdir. Önce fit sonra transform yapılır. Eğer fit ve transform metodunda aynı veri 
kümesi kullanılacaksa fit_transform metodu ile bu iki işlem bir arada yapılabilir. OrdinalEncoder sınıfının categories_ 
örnek özniteliği oluşturulan kategorileri NumPy dizisi olarak vermektedir. Sınıfın n_features_in_ örnek özniteliği ise 
fit işlemine sokulan sütunların sayısını vermektedir.

OrdinalEncoder sınıfı encode edilecek sütunları eğer onlar yazısal biçimdeyse "lexicographic" sıraya göre numaralandırmaktadır. 
(Yani sözlükte ilk gördüğü kategoriye düşük numara vermektedir. Tabii bu işlem UNICODE tabloya göre yapılmaktadır.) Kategorilere 
bizim istediğimiz numaraları vermemektedir. Ayrıca bu sınıfın fit ve transform metotları iki boyutlu nesneleri kabul etmektedir. 
Bu bağlamda OrdinalEncoder sınıfının LabelEncoder sınıfındne en önemli farklılığı OrdinalEncoder sınıfının birden fazla sütunu 
(özelliği) kabul etmesidir. Halbuki LabelEncoder sınıfı tek bir sütunu (özelliği) dönüştürmektedir.Örneğin "test.csv" veri 
kümemiz şöyle olsun:

AdıSoyadı,Kilo,Boy,Yaş,Cinsiyet,RenkTercihi,EğitimDurumu
Sacit Bulut,78,172,34,Erkek,Kırmızı,İlkokul
Ayşe Er,67,168,45,Kadın,Yeşil,Ortaokul
Ahmet San,85,182,32,Erkek,Kırmızı,İlkokul
Macit Şen,98,192,65,Erkek,Mavi,Lise
Talat Demir,85,181,49,Erkek,Yeşil,Üniversite
Sibel Ünlü,72,172,34,Kadın,Mavi,Ortaokul
Ali Serçe,75,165,21,Erkek,Yeşil,İlkokul

Burada "Cinsiyet" ve "RenkTercihi" kategorik (nominal) ölçekte sütunlardır. "EğitimDurumu" sütunu kategorik ya da sıralı
olarak ele alınabilir. Eğer biz İlkokul = 0, Ortaokul = 1, Lise = 2, Üniversite = 3 biçiminde sıralı ölçeğe ilişkin bir 
kodlama yapmak istersek bunu LabelEncoder ya da OrdinalEncoder ile sağlayamayız. Örneğin:

df = pd.read_csv('test.csv')
print(df, end='\n\n')

oe = OrdinalEncoder()
transformed_data = oe.fit_transform(df[['Cinsiyet', 'RenkTercihi', 'EğitimDurumu']])
df[['Cinsiyet', 'RenkTercihi', 'EğitimDurumu']] = transformed_data

Buradan şöyle bir DataFrame elde edilecektir:

        AdıSoyadı  Kilo  Boy  Yaş  Cinsiyet  RenkTercihi  EğitimDurumu
0  Sacit Bulut    78  172   34       0.0           0.0            3.0
1      Ayşe Er    67  168   45       1.0           2.0            1.0
2    Ahmet San    85  182   32       0.0           0.0            3.0
3    Macit Şen    98  192   65       0.0           1.0            0.0
4  Talat Demir    85  181   49       0.0           2.0            2.0
5   Sibel Ünlü    72  172   34       1.0           1.0            1.0
6    Ali Serçe    75  165   21       0.0           2.0            3.0

Bunu OridinalEncoder sınıfı le kodlamaya çalışırsak muhtemelen tam istediğimiz gibi bir kodlama yapamayız. 

"""


In [11]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv('test.csv')
print(df, end='\n\n')

oe = OrdinalEncoder()
transformed_data = oe.fit_transform(df[['Cinsiyet', 'Renk Tercihi', 'Eğitim Durumu']])

df[['Cinsiyet', 'Renk Tercihi', 'Eğitim Durumu']] = transformed_data
                                    
print(df)

    Adı Soyadı  Kilo  Boy  Yaş Cinsiyet Renk Tercihi Eğitim Durumu
0  Sacit Bulut    78  172   34    Erkek      Kırmızı       İlkokul
1      Ayşe Er    67  168   45    Kadın        Yeşil          Lise
2    Ahmet San    85  182   32    Erkek      Kırmızı      Ortaokul
3    Macit Şen    98  192   65    Erkek         Mavi    Üniversite
4  Talat Demir    85  181   49    Erkek        Yeşil          Lise
5   Sibel Ünlü    72  172   34    Kadın         Mavi    Üniversite
6    Ali Serçe    75  165   21    Erkek        Yeşil    Üniversite

    Adı Soyadı  Kilo  Boy  Yaş  Cinsiyet  Renk Tercihi  Eğitim Durumu
0  Sacit Bulut    78  172   34       0.0           0.0            3.0
1      Ayşe Er    67  168   45       1.0           2.0            0.0
2    Ahmet San    85  182   32       0.0           0.0            1.0
3    Macit Şen    98  192   65       0.0           1.0            2.0
4  Talat Demir    85  181   49       0.0           2.0            0.0
5   Sibel Ünlü    72  172   34       1.0   

In [1]:
"""
Bu durumda eğer kategorilere istediğiniz gibi değer vermek istiyorsanız bunu manuel bir biçimde yapabilirsiniz. Örneğin 
veri kümesi read_csv fonksiyonuyla okunurken converters parametresi yoluyla hemen dönüştürme yapılabilir. read_csv ve 
load_txt fonksiyonlarında converters parametresi bir sözlük nesnesi almaktadır. Bu sözlük nesnesi hangi sütun değerleri 
okunurken hangi dönüştürmenin yapılacağını belirtmektedir. Buradaki sözlüğün her elemanının anahtarı bir sütun indeksinden 
ya da sütun indeksinden değeri ise o sütunun dönüştürülmesinde kullanılacak fonksiyondan oluşmaktadır. Tabii bu fonksiyon
lambda ifadesi olarak da girilebilir. Örneğin:

df = pd.read_csv('test.csv', converters={'EğitimDurumu': lambda s: {'İlkokul': 0, 'Ortaokul': 1, 'Lise': 2, 'Üniversite': 3}[s]})

Elde edilecek DataFrame nesnesi şöyle olacaktır:

        AdıSoyadı  Kilo  Boy  Yaş Cinsiyet RenkTercihi  EğitimDurumu
0  Sacit Bulut    78  172   34    Erkek      Kırmızı              0
1      Ayşe Er    67  168   45    Kadın        Yeşil              1
2    Ahmet San    85  182   32    Erkek      Kırmızı              0
3    Macit Şen    98  192   65    Erkek         Mavi              2
4  Talat Demir    85  181   49    Erkek        Yeşil              3
5   Sibel Ünlü    72  172   34    Kadın         Mavi              1
6    Ali Serçe    75  165   21    Erkek        Yeşil              0

"""
import pandas as pd

df = pd.read_csv('test.csv', converters={'EğitimDurumu': lambda s: {'İlkokul': 0, 'Ortaokul': 1, 'Lise': 2, 'Üniversite': 3}[s]})
print(df, end='\n\n')

    Adı Soyadı  Kilo  Boy  Yaş Cinsiyet Renk Tercihi Eğitim Durumu
0  Sacit Bulut    78  172   34    Erkek      Kırmızı       İlkokul
1      Ayşe Er    67  168   45    Kadın        Yeşil          Lise
2    Ahmet San    85  182   32    Erkek      Kırmızı      Ortaokul
3    Macit Şen    98  192   65    Erkek         Mavi    Üniversite
4  Talat Demir    85  181   49    Erkek        Yeşil          Lise
5   Sibel Ünlü    72  172   34    Kadın         Mavi    Üniversite
6    Ali Serçe    75  165   21    Erkek        Yeşil    Üniversite



In [ ]:
#One-hot encoder
"""
Kategorik verilerin 0'dan itibaren LabelEncoder ya da OrdinalEncoder sınıfı ile sayısallaştırılması iyi bir fikir değildir. 
Çünkü bu durumda sanki veri "sıralı (ordinal)" bir biçime sokulmuş gibi olur. Pek çok algoritma bu durumdan olumsuz yönde 
etkilenmektedir. Örneğin veri kümesinin bir sütununda "RenkTercihi" olsun. Bu RenkTercihi de "Kırmızı", "Mavi" ve Yeşil
renklerindne oluşuyor olsun. Biz bu sütunu LabelEncoder ile sayısal hale getirdiğimizde örneğin Kırmızı = 0, Mavi = 1, 
Yeşil = 2 biçiminde renklere numara verilecektir. 

İşte burada makine öğrenmesi algoritmaları sanki "Mavi" > "Kırmızı", "Yeşil > "Mavi" gibi bir durum varmış gibi sonuca yol açabilecektir. Hatta örneğin bu kodlamadan "Kırmızı" + "Mavi" = "Mavi"
gibi gerçekte var olmayan özellikler de ortaya çıkacaktır. İşte bu nedenle kategorik olguların birden fazla sütunla ifade edilmesi 
yoluna gidilmektedir. Kategorik verilerin birden fazla sütunla ifade edilmesinde en yaygın kullanılan yöntem "one hot encoding" 
denilen yöntemdir. Bu yöntemde sütundaki kategorilerin sayısı hesaplanır. Veri tablosuna bu sayıda sütun eklenir. "One hot" 
terimi "bir grup bitten hepsinin sıfır yalnızca bir tanesinin 1 olma durumunu" anlatmaktadır. İşte bu biçimde n tane kategori 
n tane sütunla ifade edilir. Her kategori yalnızca tek bir sütunda 1 diğer sütunlarda 0 olacak biçimde kodlanır. Örneğin:

RenkTercihi
-----------
Kırmızı
Kırmızı
Mavi
Kırmızı
Yeşil
Mavi
Yeşil
...

Burada 3 renk olduğunu düşünelim. Bunun "one hot encoding" dönüştürmesi şöyle olacaktır:

Kırmızı     Mavi        Yeşil
1           0           0
1           0           0
0           1           0
1           0           0
0           0           1
0           1           0
0           0           1
...

Eğer sütundaki kategori sayısı 2 tane ise böyle sütunlar üzerinde "one hot encoding" uygulamanın bir faydası yoktur. Bu tür 
ikili sütunlar 0 ve 1 biçiminde kodlanabilir. (Yani bu işlem LabelEncoder sınıfiyla yapılabilir). Biz de kursumuzda yalnızca
iki kategori içeren sütunları "one hot encoding" ile kodlamayacağız.

"""

In [9]:
"""
"One hot encoding" yapmanın çok çeşitli yöntemleri vardır. Örneğin scikit-learn içerisindeki preprocessing modülünde bulunan 
OneHotEncoder sınıfı bu işlem için kullanılabilir. Sınıfın genel kullanımı diğer sckit-learn sınıflarında olduğu gibidir. 
Yani önce fit işllemi sonra transform işlemi yapılır. fit işleminden sonra sütunlardaki "tek olan (unique)" elemanlar sınıfın 
categories_ örnek özniteliğine NumPy dizilerinden oluşan bir liste biçiminde kaydedilmektedir. Örneğimizde kullanacağımız 
test.csv" dosyası şöyle olsun:

AdıSoyadı,Kilo,Boy,Yaş,RenkTercihi
Sacit Bulut,78,172,34,Kırmızı
Ayşe Er,67,168,45,Yeşil
Ahmet San,85,182,32,Kırmızı
Macit Şen,98,192,65,Mavi
Talat Demir,85,181,49,Yeşil
Sibel Ünlü,72,172,34,Mavi
Ali Serçe,75,165,21,Yeşil

"One hot encoding" yapılırken DataFrame içerisine eski sütunu silip yeni sütunlar eklenmelidir. DataFrame sütununa bir isim 
vererek atama yapılırsa nesne o sütunu zaten otomatik eklemektedir. "One hot encoding" ile oluşturulan sütunların isimleri önemli 
değildir. Ancak OneHotEncoder nesnesi önce sütunu np.unique fonksiyonuna sokmakta ondan sonra o sırada encoding işlemi 
yapmaktadır. NumPy'ın unique fonksiyonu aynı zamanda sıraya dizme işlemini de zaten yapmaktadır. Dolayısıyla OneHotEncoder 
aslında kategorik değerleri alfabetik sıraya göre sütunsal olarak dönüştürmektedir. Yukarıda da belirttiğimiz gibi OneHotEncoder 
nesnesi fit işlemi yapıldığında zaten kategorileri categories_ isimli örnek özniteliği yoluyla bir NumPy dizi listesi olarak 
bize vermektedir. Biz DataFrame eklemesi yaparken doğrudan bu isimleri kullanabiliriz. categories_ örnek özniteliğinin bir liste
olduğuna dikkat ediniz. Çünkü birden fazla sütun tek hamlede "one hot encoding" yapılabilmektedir. Dolayısıyla programcı bu listenin 
ilgili elemanından kategorileri elde etmelidir. 

Yukarıda da belirttiğimiz gibi OneHotEncoder sınıfının fit ve transform metotları çok boyutlu dizileri kabul etmektedir. 
Bu durumda biz bu metotlara Pandas'ın Series nesnesini değil DataFrame nesnesini vermeliyiz.

OneHotEncoder nesnesini yaratırken "sparse_output" parametresini False biçimde vermeyi unutmayınız. (Bu parametrenin eski 
ismi yalnızca "sparse" biçimindeydi). Çünkü bu sınıf default olarak transform edilmiş nesneyi "seyrek matris (sparse matrix)" 
olarak vermektedir. Elemanlarının büyük çoğunluğu 0 olan matrislere "seyrek matris (sparse matrix)" denilmektedir. Bu tür 
matrisler "fazla yer kaplamasın diye" sıkıştırılmış bir biçimde ifade edilebilmektedir. Seyrek matrisler üzerinde işlemler 
kursumuzun sonraki bölümlerinde ele alınacaktır.

Yine OneHotEncoder nesnesi yaratılırken parametre olarak dtype türünü belirtebiliriz. Default dtype türü np.float64 alınmaktadır. 
Matris seyrek formda elde edilmeyecekse bu dtype türünü "uint8" gibi en küçük türde tutabilirsiniz. max_categories parametresi 
kategori sayısını belli bir değerde tutmak için kullanılmaktadır. Bu durumda diğer tüm kategoriler başka bir kategori oluşturmaktadır.

Örneğin:

df = pd.read_csv('test.csv')
ohe = OneHotEncoder(sparse_output=False, dtype='uint8')
transformed_data = ohe.fit_transform(df[['RenkTercihi']])
df.drop(['RenkTercihi'], axis=1, inplace=True)
df[ohe.categories_[0]] = transformed_data

Burada önce veri kümesi okunmuş sonra OneHotEncoder sınıfıyla fit_transform işlemi yapılmıştır. Daha sonra ise DataFrame 
içerisindeki "RenkTercihi" sütunu silinip onun yerine categories_ örnek özniteliğindeki kategori isimleri nesneye eklenmiştir.
"""
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('test.csv')

ohe = OneHotEncoder(sparse=False, dtype='uint8')
transformed_data = ohe.fit_transform(df[['RenkTercihi']])
df.drop(['RenkTercihi'], axis=1, inplace=True)
# Oluşan one-hot encoded veriyi DataFrame'e ekleyin
for i, column in enumerate(ohe.categories_[0]):
    df[column] = transformed_data[:, i]

print(df)

     AdıSoyadı  Kilo  Boy  Yaş    Meslek  Kırmızı  Mavi  Yeşil
0  Sacit Bulut    78  172   34  Mühendis        1     0      0
1      Ayşe Er    67  168   45  Mühendis        0     0      1
2    Ahmet San    85  182   32    Avukat        1     0      0
3    Macit Şen    98  192   65    Doktor        0     1      0
4  Talat Demir    85  181   49    Avukat        0     0      1
5   Sibel Ünlü    72  172   34    Doktor        0     1      0
6    Ali Serçe    75  165   21  Mühendis        0     0      1


In [8]:
"""
DataFrame nesnesine yukarıdaki gibi birden fazla sütun eklerken dikkat etmek gerekir. Çünkü tesadüfen bu kategori isimlerine
ilişkin sütunlardan biri zaten varsa o sütun yok edilip yerine bu kategori sütunu oluşturulacaktır. Bunu engellemek için 
oluşturacağınız kategori sütunlarını önek vererek isimlendirebilirsiniz. Önek verirken orijinal sütun ismini kullanırsanız
bu durumda çakışma olmayacağı garanti edilebilir. Yani örneğin RenkTercihi sütunu için "Kırmızı", "Mavi" "Yeşil" isimleri 
yerine "RenkTercihi_Kırmızı", "RenkTercihi_Mavi" ve "RenkTercihi_Yeşil" isimlerini kullanabilirsiniz. Bu biçimde isim elde
etmek "liste içlemiyle" oldukça kolaydır. Örneğin:

category_names = ['RenkTercihi_' + category for category in ohe.categories_[0]]

Aşağıda buna örnek verilmiştir. 

"""
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('test.csv')

ohe = OneHotEncoder(sparse=False, dtype='uint8')

transformed_data = ohe.fit_transform(df[['RenkTercihi']])

df.drop(['RenkTercihi'], axis=1, inplace=True)

category_names = ['RenkTercihi_' + category for category in ohe.categories_[0]]
df[category_names] = transformed_data

print(df)

     AdıSoyadı  Kilo  Boy  Yaş    Meslek  RenkTercihi_Kırmızı  \
0  Sacit Bulut    78  172   34  Mühendis                    1   
1      Ayşe Er    67  168   45  Mühendis                    0   
2    Ahmet San    85  182   32    Avukat                    1   
3    Macit Şen    98  192   65    Doktor                    0   
4  Talat Demir    85  181   49    Avukat                    0   
5   Sibel Ünlü    72  172   34    Doktor                    0   
6    Ali Serçe    75  165   21  Mühendis                    0   

   RenkTercihi_Mavi  RenkTercihi_Yeşil  
0                 0                  0  
1                 0                  1  
2                 0                  0  
3                 1                  0  
4                 0                  1  
5                 1                  0  
6                 0                  1  


In [6]:
"""
Veri kümesinde birden fazla sütunda kategorik bilgiler olabilir. Bunlar OneHotEncoder sınıfıyla tek tek kodlanabilirler. 
Ancak aslında yukarıda da belirttiğimiz gibi OneHotEncoder sınıfı bir grup sütunu tek hamlede de kodlayabilmektedir. 
Örneğin "test.csv" veri kümemiz şöyle olsun:

AdıSoyadı,Kilo,Boy,Yaş,RenkTercihi,Meslek
Sacit Bulut,78,172,34,Kırmızı,Mühendis
Ayşe Er,67,168,45,Yeşil,Mühendis
Ahmet San,85,182,32,Kırmızı,Avukat
Macit Şen,98,192,65,Mavi,Doktor
Talat Demir,85,181,49,Yeşil,Avukat
Sibel Ünlü,72,172,34,Mavi,Doktor
Ali Serçe,75,165,21,Yeşil,Mühendis

Burada "RenkTercihi"nin yanı sıra "Meslek" de kategorik bir sütundur. Bunun her ikisini birden tek hamlede "one hot encoding" 
işlemine sokabiliriz:

"""
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('test.csv')

ohe = OneHotEncoder(sparse=False, dtype='uint8')

transformed_data = ohe.fit_transform(df[['RenkTercihi', 'Meslek']])

df.drop(['RenkTercihi', 'Meslek'], axis=1, inplace=True)

categories1 = ['RenkTercihi_' + category for category in ohe.categories_[0]]
categories2 = ['Meslek_' + category for category in ohe.categories_[1]]

df[categories1 + categories2] = transformed_data

print(df)

     AdıSoyadı  Kilo  Boy  Yaş  RenkTercihi_Kırmızı  RenkTercihi_Mavi  \
0  Sacit Bulut    78  172   34                    1                 0   
1      Ayşe Er    67  168   45                    0                 0   
2    Ahmet San    85  182   32                    1                 0   
3    Macit Şen    98  192   65                    0                 1   
4  Talat Demir    85  181   49                    0                 0   
5   Sibel Ünlü    72  172   34                    0                 1   
6    Ali Serçe    75  165   21                    0                 0   

   RenkTercihi_Yeşil  Meslek_Avukat  Meslek_Doktor  Meslek_Mühendis  
0                  0              0              0                1  
1                  1              0              0                1  
2                  0              1              0                0  
3                  0              0              1                0  
4                  1              1              0               

In [11]:
"""
Aslında makine öğrenmesi uygulamalarında veri kümesinin sütun isimlerinin hiçbir önemi yoktur. Dolayısıyla aslında biz 
"one hot encoding" işleminden önce NumPy dizisine geçip hiç isimlerini oluşturmadan geri kalan kısmı NumPy üzerinde de 
yapabiliriz. Aşağıda buna bir örnek verilmektedir.
"""
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('test.csv')

ohe = OneHotEncoder(sparse=False, dtype='uint8')
transformed_data = ohe.fit_transform(df[['RenkTercihi', 'Meslek']])

df.drop(['AdıSoyadı', 'RenkTercihi', 'Meslek'], axis=1, inplace=True)

dataset = df.to_numpy()
dataset = np.concatenate((dataset, transformed_data), axis=1)

print(dataset)

[[ 78 172  34   1   0   0   0   0   1]
 [ 67 168  45   0   0   1   0   0   1]
 [ 85 182  32   1   0   0   1   0   0]
 [ 98 192  65   0   1   0   0   1   0]
 [ 85 181  49   0   0   1   1   0   0]
 [ 72 172  34   0   1   0   0   1   0]
 [ 75 165  21   0   0   1   0   0   1]]


In [12]:
"""
One hot encoding yapmanın diğer bir yolu Pandas kütüphanesindeki get_dummies fonksiyonunu kullanmaktadır. get_dummies fonksiyonu
bizden bir DataFrame, Series ya da dolaşılabilir herhangi bir nesneyi alır. Eğer biz get_dummies fonksiyonuna bütün bir DataFrame
geçirirsek fonksiyon oldukça akıllı davranmaktadır. Bu durumda fonksiyon DataFrame nesnesi içerisindeki yazısal sütunları tespit 
eder. Yalnızca yazısal sütunları "one hot encoding" işlemine sokar ve bize yazısal sütunları dönüştürülmüş yeni bir DataFrame
nesnesi verir. Pandas ile çalışırken bu fonksiyon çok kolaylık sağlamaktadır. yine "test.csv" veri kümemiz şöyle olsun:

AdıSoyadı,Kilo,Boy,Yaş,RenkTercihi,Meslek
Sacit Bulut,78,172,34,Kırmızı,Mühendis
Ayşe Er,67,168,45,Yeşil,Mühendis
Ahmet San,85,182,32,Kırmızı,Avukat
Macit Şen,98,192,65,Mavi,Doktor
Talat Demir,85,181,49,Yeşil,Avukat
Sibel Ünlü,72,172,34,Mavi,Doktor
Ali Serçe,75,165,21,Yeşil,Mühendis

Biz aslında get_dummies fonksiyonu yoluyla yapmış olduğumuz işlemleri tek hamlede yapabiliriz:

df = pd.read_csv('test.csv')
transformed_df = pd.get_dummies(df, dtype='uint8')

Burada biz tek hamlede istediğimiz dönüştürmeyi yapabildik. Bu dönüştürmede yine sütun isimleri orijinal sütun isimleri 
ve kategori simleriyle öneklendirilmiştir. Eğer isterse programcı "prefix" parametresi ile bu öneki değiştirebilir, "prefix_sep"
parametresiyle de '_' karakteri yerine başka birleştirme karakterlerini kullanabilir. get_dummies fonksiyonu default durumda 
sparse olmayan bool türden bir DataFrame nesnesi vermektedir. Ancak get_dummies fonksiyonunda "dtype" parametresi belirtilerek 
"uint8" gibi bir türden çıktı oluşturulması sağlanabilmektedir. 

Biz bir DataFrame nesnesinin tüm yazısal sütunlarını değil bazı yazısal sütunlarını da "one hot encoding" işlemine sokmak 
isteyebiliriz. Bu durumda fonksiyon DataFrame nesnesinin diğer sütunlarına hiç dokunmamaktadır. Örneğin:

transformed_df = pd.get_dummies(df, columns=['Meslek'], dtype='uint8')

Biz burada yalnızca DataFrame nesnesinin "Meslek" sütununu "one hot encoding" yapmış olduk. get_dummies fonksiyonun zaten 
"one hot encoding" yapılan sütunu sildiğine dikkat ediniz. Bu bizim genellikle istediğimiz bir şeydir. Yukarıdaki örnekte 
"test.csv" dosyasında "AdıSoyadı" sütunu yazısal bir sütundur. Dolayısıyla default durumda bu sütun da "one hot encoding" 
işlmeine sokulacaktır. Bunu engellemek için "columns" parametresinden faydalanabiliriz ya da baştan o sütunu atabiliriz. 
Örneğin:

transformed_df = pd.get_dummies(df.iloc[:, 1:], dtype='uint8')

"""
import pandas as pd

df = pd.read_csv('test.csv')

print(df, end='\n\n')

ohe_df = pd.get_dummies(df, columns=['RenkTercihi', 'Meslek'])

print(ohe_df)


     AdıSoyadı  Kilo  Boy  Yaş RenkTercihi    Meslek
0  Sacit Bulut    78  172   34     Kırmızı  Mühendis
1      Ayşe Er    67  168   45       Yeşil  Mühendis
2    Ahmet San    85  182   32     Kırmızı    Avukat
3    Macit Şen    98  192   65        Mavi    Doktor
4  Talat Demir    85  181   49       Yeşil    Avukat
5   Sibel Ünlü    72  172   34        Mavi    Doktor
6    Ali Serçe    75  165   21       Yeşil  Mühendis

     AdıSoyadı  Kilo  Boy  Yaş  RenkTercihi_Kırmızı  RenkTercihi_Mavi  \
0  Sacit Bulut    78  172   34                    1                 0   
1      Ayşe Er    67  168   45                    0                 0   
2    Ahmet San    85  182   32                    1                 0   
3    Macit Şen    98  192   65                    0                 1   
4  Talat Demir    85  181   49                    0                 0   
5   Sibel Ünlü    72  172   34                    0                 1   
6    Ali Serçe    75  165   21                    0             

In [13]:
"""
Yukarıda da belirttiğimiz gibi get_dummies fonksiyonu default durumda oluşturduğu sütunlara kategorik sütun isimlerini ve 
kategoroileri '_' ile birleştirerek vermektedir. Ancak bir istersek prefix parametresi ile bu önekleri değiştirebiliriz. 
Örneğin:

df = pd.read_csv('test.csv')

transformed_df = pd.get_dummies(df, columns=['RenkTercihi', 'Meslek'], dtype='uint8', prefix=['R', 'M'])

Burada oluşturulacak sütunlar için önekler sırasıyla 'R' ve 'M' biçiminde verilmiştir.

"""
import pandas as pd

df = pd.read_csv('test.csv')

transformed_df = pd.get_dummies(df, columns=['RenkTercihi', 'Meslek'], dtype='uint8', prefix=['R', 'M'])
print(transformed_df)


     AdıSoyadı  Kilo  Boy  Yaş  R_Kırmızı  R_Mavi  R_Yeşil  M_Avukat  \
0  Sacit Bulut    78  172   34          1       0        0         0   
1      Ayşe Er    67  168   45          0       0        1         0   
2    Ahmet San    85  182   32          1       0        0         1   
3    Macit Şen    98  192   65          0       1        0         0   
4  Talat Demir    85  181   49          0       0        1         1   
5   Sibel Ünlü    72  172   34          0       1        0         0   
6    Ali Serçe    75  165   21          0       0        1         0   

   M_Doktor  M_Mühendis  
0         0           1  
1         0           1  
2         0           0  
3         1           0  
4         0           0  
5         1           0  
6         0           1  


In [1]:
"""
Yine yukarıda belirttiğimiz gibi sütun isimlerinin birleştirilmesi için kullanılan karakter prefix_sep isimli parametreyle 
değiştirilebilmektedir. Örneğin:

df = pd.read_csv('test.csv')

transformed_df = pd.get_dummies(df, columns=['RenkTercihi', 'Meslek'], dtype='uint8', prefix=['R', 'M'], prefix_sep='-')

Burada artık önekler 'R-' ve 'M-' haline getirilmiştir.

"""
import pandas as pd

df = pd.read_csv('test.csv')

transformed_df = pd.get_dummies(df, columns=['RenkTercihi', 'Meslek'], dtype='uint8', prefix=['R', 'M'], prefix_sep='-')
print(transformed_df)

     AdıSoyadı  Kilo  Boy  Yaş  R-Kırmızı  R-Mavi  R-Yeşil  M-Avukat  \
0  Sacit Bulut    78  172   34          1       0        0         0   
1      Ayşe Er    67  168   45          0       0        1         0   
2    Ahmet San    85  182   32          1       0        0         1   
3    Macit Şen    98  192   65          0       1        0         0   
4  Talat Demir    85  181   49          0       0        1         1   
5   Sibel Ünlü    72  172   34          0       1        0         0   
6    Ali Serçe    75  165   21          0       0        1         0   

   M-Doktor  M-Mühendis  
0         0           1  
1         0           1  
2         0           0  
3         1           0  
4         0           0  
5         1           0  
6         0           1  
